services:
  zwave-js:
    container_name: zwave-js
    image: zwavejs/zwave-js-ui:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=${ZWAVE_SESSION_SECRET}
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      - TZ=${TZ}
    devices:
      - /dev/serial/by-id/${ZWAVE_USB_DEVICE_ID}:/dev/zwave
    volumes:
      - ${USERDIR:-$HOME}/docker/zwave-js:/usr/src/app/store
    networks:
      - dnet
    ports:
      - 3000:3000  # Websocket Server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zwave-js.rule=Host(`${ZWAVE_HOST}`)"
      - "traefik.http.routers.zwave-js.entrypoints=web"
      - "traefik.http.services.zwave-js.loadbalancer.server.port=8091"

networks:
  dnet:
    external: true
